# Generated by Django 5.2.1 on 2025-05-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('place_type', models.CharField(default='city', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('rating', models.FloatField(default=0.0)),
                ('visit_duration', models.CharField(default='1-2 hours', max_length=50)),
                ('best_time', models.CharField(default='Any time', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TouristAttraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('rating', models.FloatField(default=0.0)),
                ('visit_duration', models.CharField(default='1-2 hours', max_length=50)),
                ('best_time', models.CharField(default='Any time', max_length=100)),
                ('distance_from_route', models.FloatField(default=0.0)),
                ('detour_time', models.CharField(default='0 min', max_length=50)),
                ('historical_significance', models.TextField(blank=True)),
                ('local_tips', models.TextField(blank=True)),
            ],
        ),
    ]
