# Generated by Django 5.2.1 on 2025-05-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Touristapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedRouteData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_city', models.CharField(max_length=100)),
                ('end_city', models.CharField(max_length=100)),
                ('start_lat', models.FloatField()),
                ('start_lon', models.FloatField()),
                ('end_lat', models.FloatField()),
                ('end_lon', models.FloatField()),
                ('route_geometry', models.JSONField()),
                ('all_places', models.JSONField()),
                ('top_places', models.JSONField()),
                ('recommendations', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('start_city', 'end_city')},
            },
        ),
    ]
