# Generated by Django 5.2.1 on 2025-05-29 15:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Touristapp', '0002_cachedroutedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachedroutedata',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
