# Generated by Django 5.2.1 on 2025-05-29 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Touristapp', '0003_alter_cachedroutedata_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_city', models.CharField(max_length=100)),
                ('end_city', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('start_city', 'end_city')},
            },
        ),
        migrations.DeleteModel(
            name='CachedRouteData',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.RemoveField(
            model_name='touristattraction',
            name='best_time',
        ),
        migrations.RemoveField(
            model_name='touristattraction',
            name='detour_time',
        ),
        migrations.RemoveField(
            model_name='touristattraction',
            name='historical_significance',
        ),
        migrations.RemoveField(
            model_name='touristattraction',
            name='local_tips',
        ),
        migrations.RemoveField(
            model_name='touristattraction',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='touristattraction',
            name='visit_duration',
        ),
        migrations.AlterField(
            model_name='touristattraction',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='touristattraction',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='Touristapp.routequery'),
        ),
    ]
