# Generated by Django 5.2.1 on 2025-05-30 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Touristapp', '0004_routequery_delete_cachedroutedata_delete_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routequery',
            name='route_geometry_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
